### PR TITLE
Development

### PR DESCRIPTION
**Pull request by angarita-dev**
Master <-- Development

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
Hi @codingAngarita, 
Great work, just few things to do and have :+1:  , kindly do the following;
1. HTML file structuring, kindly visit this [link](https://www.themelocation.com/best-html5-practices) and apply the right way of using tags.
2. Run your code :point_right: [here](https://validator.w3.org)  and fix the errors.
[i ran your code on w3 validator, you have few errors that need to be fix]

After fixing the HTML tags issues and the validation errors please send another request to re-review this project.

**Comment by angarita-dev** [comment]
Hi! I just made changes in the HTML to make it more semantic using the link you provided, also I checked for errors but didn't find any
w3 validator for html

**Comment by bellom** [comment]
Hi @codingAngarita, well, for some reasons you are not seeing the errors from your end.
But i could see some at my end, checkout the screenshot below;
image
kindly fix these errors, while your :+1: await you......

**Review by bellom — APPROVED** [review]
Hi @codingAngarita,
## Congratulation :+1: , what a great work fixing all the errors!!
_Go ahead and merge and don't forget to submit your project completion form_
Goodluck in the next project. :slightly_smiling_face:

**Pull request merged**
